# Use root/example as user/password credentials

# TODO: make this configurable
version: '3.3'
services:
  db:
    image: mysql:8.0.0
    restart: always
    container_name: prisma-mysql
    environment:
      MYSQL_DATABASE: 'prisma'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'user'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'user'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'